name: .zip Pack

on: [push]
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vimtor/action-zip@v1.1
        with:
          files: /markers
          recursive: true
          dest: Hero.Blish.Pack.zip
      - uses: actions/upload-artifact@v3
        with:
          name: Heros-Marker-Pack-Artifact
          path: ${{ github.workspace }}/Hero.Blish.Pack.zip